-- MySQL Script generated by MySQL Workbench
-- 03/12/16 16:59:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema heuristica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heuristica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heuristica` DEFAULT CHARACTER SET utf8 ;
USE `heuristica` ;

-- -----------------------------------------------------
-- Table `heuristica`.`Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`Docente` (
  `idDocente` VARCHAR(20) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `admin` TINYINT(1) NOT NULL,
  `habilitado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idDocente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`Asignatura` (
  `idAsignatura` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAsignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`Seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`Seccion` (
  `idSeccion` VARCHAR(5) NOT NULL,
  `Docente_idDocente` VARCHAR(20) NOT NULL,
  `Asignatura_idAsignatura` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idSeccion`),
  INDEX `fk_Seccion_Docente1_idx` (`Docente_idDocente` ASC),
  INDEX `fk_Seccion_Asignatura1_idx` (`Asignatura_idAsignatura` ASC),
  CONSTRAINT `fk_Seccion_Docente1`
    FOREIGN KEY (`Docente_idDocente`)
    REFERENCES `heuristica`.`Docente` (`idDocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seccion_Asignatura1`
    FOREIGN KEY (`Asignatura_idAsignatura`)
    REFERENCES `heuristica`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`Alumno` (
  `idAlumno` VARCHAR(20) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `habilitado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`AlumnoSeccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`AlumnoSeccion` (
  `idAlumnoSeccion` INT NOT NULL,
  `Seccion_idSeccion` VARCHAR(5) NOT NULL,
  `Alumno_idAlumno` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idAlumnoSeccion`),
  INDEX `fk_AlumnoSeccion_Seccion1_idx` (`Seccion_idSeccion` ASC),
  INDEX `fk_AlumnoSeccion_Alumno1_idx` (`Alumno_idAlumno` ASC),
  CONSTRAINT `fk_AlumnoSeccion_Seccion1`
    FOREIGN KEY (`Seccion_idSeccion`)
    REFERENCES `heuristica`.`Seccion` (`idSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AlumnoSeccion_Alumno1`
    FOREIGN KEY (`Alumno_idAlumno`)
    REFERENCES `heuristica`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`Rubrica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`Rubrica` (
  `idRubrica` INT NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`idRubrica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`UnidadAprendizaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`UnidadAprendizaje` (
  `idUnidadAprendizaje` INT NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  `Rubrica_idRubrica` INT NOT NULL,
  PRIMARY KEY (`idUnidadAprendizaje`),
  INDEX `fk_UnidadAprendizaje_Rubrica1_idx` (`Rubrica_idRubrica` ASC),
  CONSTRAINT `fk_UnidadAprendizaje_Rubrica1`
    FOREIGN KEY (`Rubrica_idRubrica`)
    REFERENCES `heuristica`.`Rubrica` (`idRubrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`RecursosDidacticos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`RecursosDidacticos` (
  `idRecursosDidacticos` INT NOT NULL,
  `UnidadAprendizaje_idUnidadAprendizaje` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`idRecursosDidacticos`),
  INDEX `fk_RecursosDidacticos_UnidadAprendizaje1_idx` (`UnidadAprendizaje_idUnidadAprendizaje` ASC),
  CONSTRAINT `fk_RecursosDidacticos_UnidadAprendizaje1`
    FOREIGN KEY (`UnidadAprendizaje_idUnidadAprendizaje`)
    REFERENCES `heuristica`.`UnidadAprendizaje` (`idUnidadAprendizaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`Grupo` (
  `idGrupo` INT NOT NULL,
  `UnidadAprendizaje_idUnidadAprendizaje` INT NOT NULL,
  PRIMARY KEY (`idGrupo`),
  INDEX `fk_Grupo_UnidadAprendizaje1_idx` (`UnidadAprendizaje_idUnidadAprendizaje` ASC),
  CONSTRAINT `fk_Grupo_UnidadAprendizaje1`
    FOREIGN KEY (`UnidadAprendizaje_idUnidadAprendizaje`)
    REFERENCES `heuristica`.`UnidadAprendizaje` (`idUnidadAprendizaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`AlumnosGrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`AlumnosGrupo` (
  `idAlumnosGrupo` INT NOT NULL,
  `Alumno_idAlumno` VARCHAR(200) NOT NULL,
  `Grupo_idGrupo` INT NOT NULL,
  PRIMARY KEY (`idAlumnosGrupo`),
  INDEX `fk_AlumnosGrupo_Alumno1_idx` (`Alumno_idAlumno` ASC),
  INDEX `fk_AlumnosGrupo_Grupo1_idx` (`Grupo_idGrupo` ASC),
  CONSTRAINT `fk_AlumnosGrupo_Alumno1`
    FOREIGN KEY (`Alumno_idAlumno`)
    REFERENCES `heuristica`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AlumnosGrupo_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `heuristica`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`Criterio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`Criterio` (
  `idCriterio` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCriterio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`NivelCompetencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`NivelCompetencia` (
  `idNivelCompetencia` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Puntaje` INT NOT NULL,
  PRIMARY KEY (`idNivelCompetencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`CriterioNivelRubrica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`CriterioNivelRubrica` (
  `idCriterioNivelRubrica` INT NOT NULL,
  `Criterio_idCriterio` INT NOT NULL,
  `NivelCompetencia_idNivelCompetencia` INT NOT NULL,
  `Rubrica_idRubrica` INT NOT NULL,
  PRIMARY KEY (`idCriterioNivelRubrica`),
  INDEX `fk_CriterioNivelRubrica_Criterio1_idx` (`Criterio_idCriterio` ASC),
  INDEX `fk_CriterioNivelRubrica_NivelCompetencia1_idx` (`NivelCompetencia_idNivelCompetencia` ASC),
  INDEX `fk_CriterioNivelRubrica_Rubrica1_idx` (`Rubrica_idRubrica` ASC),
  CONSTRAINT `fk_CriterioNivelRubrica_Criterio1`
    FOREIGN KEY (`Criterio_idCriterio`)
    REFERENCES `heuristica`.`Criterio` (`idCriterio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CriterioNivelRubrica_NivelCompetencia1`
    FOREIGN KEY (`NivelCompetencia_idNivelCompetencia`)
    REFERENCES `heuristica`.`NivelCompetencia` (`idNivelCompetencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CriterioNivelRubrica_Rubrica1`
    FOREIGN KEY (`Rubrica_idRubrica`)
    REFERENCES `heuristica`.`Rubrica` (`idRubrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`ResultadoCoevaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`ResultadoCoevaluacion` (
  `idResultadoCoevaluacion` INT NOT NULL,
  `AlumnosGrupo_idAlumnosGrupo` INT NOT NULL,
  `CriterioNivelRubrica_idCriterioNivelRubrica` INT NOT NULL,
  `PuntajeObtenido` INT NULL,
  PRIMARY KEY (`idResultadoCoevaluacion`),
  INDEX `fk_ResultadoCoevaluacion_AlumnosGrupo1_idx` (`AlumnosGrupo_idAlumnosGrupo` ASC),
  INDEX `fk_ResultadoCoevaluacion_CriterioNivelRubrica1_idx` (`CriterioNivelRubrica_idCriterioNivelRubrica` ASC),
  CONSTRAINT `fk_ResultadoCoevaluacion_AlumnosGrupo1`
    FOREIGN KEY (`AlumnosGrupo_idAlumnosGrupo`)
    REFERENCES `heuristica`.`AlumnosGrupo` (`idAlumnosGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ResultadoCoevaluacion_CriterioNivelRubrica1`
    FOREIGN KEY (`CriterioNivelRubrica_idCriterioNivelRubrica`)
    REFERENCES `heuristica`.`CriterioNivelRubrica` (`idCriterioNivelRubrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`ResultadoRubricaEvaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`ResultadoRubricaEvaluacion` (
  `idResultadoRubricaEvaluacion` INT NOT NULL,
  `CriterioNivelRubrica_idCriterioNivelRubrica` INT NOT NULL,
  `Grupo_idGrupo` INT NOT NULL,
  `PuntajeObtenido` INT NULL,
  PRIMARY KEY (`idResultadoRubricaEvaluacion`),
  INDEX `fk_ResultadoRubricaEvaluacion_CriterioNivelRubrica1_idx` (`CriterioNivelRubrica_idCriterioNivelRubrica` ASC),
  INDEX `fk_ResultadoRubricaEvaluacion_Grupo1_idx` (`Grupo_idGrupo` ASC),
  CONSTRAINT `fk_ResultadoRubricaEvaluacion_CriterioNivelRubrica1`
    FOREIGN KEY (`CriterioNivelRubrica_idCriterioNivelRubrica`)
    REFERENCES `heuristica`.`CriterioNivelRubrica` (`idCriterioNivelRubrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ResultadoRubricaEvaluacion_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `heuristica`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`Ayuda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`Ayuda` (
  `idAyuda` INT NOT NULL,
  `procedimiento` VARCHAR(45) NULL,
  `aplicaciones` VARCHAR(45) NULL,
  `procesamiento` VARCHAR(45) NULL,
  `lenguaje` VARCHAR(45) NULL,
  `modelos` VARCHAR(45) NULL,
  `conclusiones` VARCHAR(45) NULL,
  `UnidadAprendizaje_idUnidadAprendizaje` INT NOT NULL,
  PRIMARY KEY (`idAyuda`),
  INDEX `fk_Ayuda_UnidadAprendizaje1_idx` (`UnidadAprendizaje_idUnidadAprendizaje` ASC),
  CONSTRAINT `fk_Ayuda_UnidadAprendizaje1`
    FOREIGN KEY (`UnidadAprendizaje_idUnidadAprendizaje`)
    REFERENCES `heuristica`.`UnidadAprendizaje` (`idUnidadAprendizaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`Preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`Preguntas` (
  `idPreguntas` INT NOT NULL,
  `preguntas` VARCHAR(45) NOT NULL,
  `UnidadAprendizaje_idUnidadAprendizaje` INT NOT NULL,
  PRIMARY KEY (`idPreguntas`),
  INDEX `fk_Preguntas_UnidadAprendizaje1_idx` (`UnidadAprendizaje_idUnidadAprendizaje` ASC),
  CONSTRAINT `fk_Preguntas_UnidadAprendizaje1`
    FOREIGN KEY (`UnidadAprendizaje_idUnidadAprendizaje`)
    REFERENCES `heuristica`.`UnidadAprendizaje` (`idUnidadAprendizaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heuristica`.`SeccionUnidadAprendizaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heuristica`.`SeccionUnidadAprendizaje` (
  `Seccion_idSeccion` VARCHAR(5) NOT NULL,
  `UnidadAprendizaje_idUnidadAprendizaje` INT NOT NULL,
  PRIMARY KEY (`Seccion_idSeccion`, `UnidadAprendizaje_idUnidadAprendizaje`),
  INDEX `fk_Seccion_has_UnidadAprendizaje_UnidadAprendizaje1_idx` (`UnidadAprendizaje_idUnidadAprendizaje` ASC),
  INDEX `fk_Seccion_has_UnidadAprendizaje_Seccion1_idx` (`Seccion_idSeccion` ASC),
  CONSTRAINT `fk_Seccion_has_UnidadAprendizaje_Seccion1`
    FOREIGN KEY (`Seccion_idSeccion`)
    REFERENCES `heuristica`.`Seccion` (`idSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seccion_has_UnidadAprendizaje_UnidadAprendizaje1`
    FOREIGN KEY (`UnidadAprendizaje_idUnidadAprendizaje`)
    REFERENCES `heuristica`.`UnidadAprendizaje` (`idUnidadAprendizaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
